include:
- remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - buildtest

.my-dynamic-image-name:
  extends: [.dynamic-image-name]
  before_script:
    - DOCKER_TAG=`echo $(eval cat $WATCH_FILECHANGES; echo -n $slurm_version) | sha256sum | head -c 16`
    - export PERSIST_IMAGE_NAME=$PERSIST_IMAGE_NAME:$DOCKER_TAG

build slurm base:
  extends: [.container-builder-cscs-zen2, .my-dynamic-image-name]
  stage: baseimage
  timeout: 10h
  variables:
    CSCS_NOTIFICATION_CONTEXT: "$slurm_version"
    DOCKERFILE: ci/slurm_docker/Dockerfile.base
    DOCKER_BUILD_ARGS: '["SLURM_VERSION=$slurm_version"]'
    WATCH_FILECHANGES: ci/slurm_docker/Dockerfile.base ci/slurm_docker/cgroup.conf ci/slurm_docker/entrypoint.sh ci/slurm_docker/install_slurm.sh ci/slurm_docker/slurm.conf.in
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/public/slurm-base

build:
  extends: [.container-builder-cscs-zen2]
  needs: ["build slurm base"]
  stage: buildtest
  variables:
    CSCS_REBUILD_POLICY: always
    CSCS_NOTIFICATION_CONTEXT: "$slurm_version"
    DOCKERFILE: ci/slurm_docker/Dockerfile
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}"]'
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/public/slurm-uenv-mount
