include:
- remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage x86_64
  - build x86_64
  - build rpm x86_64
  - baseimage aarch64
  - build aarch64
  - build rpm aarch64

.my-dynamic-image-name:
  extends: [.dynamic-image-name]
  before_script:
    - DOCKER_TAG=`echo $(eval cat $WATCH_FILECHANGES; echo -n $slurm_version) | sha256sum | head -c 16`
    - export PERSIST_IMAGE_NAME=$PERSIST_IMAGE_NAME:$DOCKER_TAG
    - echo "BASE_IMAGE=$PERSIST_IMAGE_NAME" > build.env

.build slurm base:
  timeout: 10h
  variables:
    CSCS_NOTIFICATION_CONTEXT: "$slurm_version"
    DOCKERFILE: ci/slurm_docker/Dockerfile.base
    DOCKER_BUILD_ARGS: '["SLURM_VERSION=$slurm_version"]'
    WATCH_FILECHANGES: ci/slurm_docker/Dockerfile.base ci/slurm_docker/cgroup.conf ci/slurm_docker/entrypoint.sh ci/slurm_docker/install_slurm.sh ci/slurm_docker/slurm.conf.in
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/public/slurm-base

build slurm base x86_64:
  stage: baseimage x86_64
  extends: [.my-dynamic-image-name, '.build slurm base', .container-builder-cscs-zen2]

build slurm base aarch64:
  stage: baseimage aarch64
  extends: [.my-dynamic-image-name, '.build slurm base', .container-builder-cscs-gh200]

.build:
  variables:
    CSCS_REBUILD_POLICY: always
    CSCS_NOTIFICATION_CONTEXT: "$slurm_version"
    DOCKERFILE: ci/slurm_docker/Dockerfile
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}"]'

build x86_64:
  needs: ["build slurm base x86_64"]
  stage: build x86_64
  extends: [.build, .container-builder-cscs-zen2]
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/public/slurm-uenv-mount-x86_64

build aarch64:
  needs: ["build slurm base aarch64"]
  stage: build aarch64
  extends: [.build, .container-builder-cscs-gh200]
  variables:
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/public/slurm-uenv-mount-aarch64

.build rpm:
  variables:
    CSCS_NOTIFICATION_CONTEXT: "$slurm_version"
  image: $CSCS_REGISTRY_PATH/base/public/slurm-uenv-mount
  script:
    - |
      _rpm_build_dir=./
      mkdir -p ${_rpm_build_dir}
      CXX=g++-12 CC=gcc-12 /src/rpm/make-rpm.sh --slurm-version "${slurm_version}" ${_rpm_build_dir}

build rpm x86_64:
  needs: ["build x86_64"]
  stage: build rpm x86_64
  extends: ['.build rpm', .container-runner-eiger-mc]

build rpm aarch64:
  needs: ["build aarch64"]
  stage: build rpm aarch64
  extends: ['.build rpm', .f7t-container-runner]
  variables:
    F7T_URL: 'https://firecrest-todi.v1.tds.cscs.ch'
    FIRECREST_SYSTEM: 'todi'
    ARCH: 'aarch64'
    USE_CE: 'YES'
