include:
- remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - buildtest

build zen2:
  extends: .container-builder-cscs-zen2
  stage: baseimage
  timeout: 10h
  variables:
    DOCKERFILE: ci/slurm_docker/Dockerfile
    WATCH_FILECHANGES: ci/slurm_docker/Dockerfile ci/slurm_docker/cgroup.conf ci/slurm_docker/entrypoint.sh ci/slurm_docker/install_slurm.sh ci/slurm_docker/slurm.conf.in
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/slurm-uenv-mount:$CI_COMMIT_SHA

build:
  extends: .container-runner-lightweight-zen2
  needs: ["build zen2"]
  stage: buildtest
  image: $CSCS_REGISTRY_PATH/base/slurm-uenv-mount:$CI_COMMIT_SHA
  script:
    - |
      meson setup builddir
      meson install -C builddir
      echo "required /usr/local/lib64/libslurm-uenv-mount.so" > /etc/slurm/plugstack.conf
      # initialization
      /entrypoint.sh
      sinfo
      echo "Run tests in bash-bats"
      su testuser -c bash <<\EOF
      bats ci/tests
      EOF
