name: Build Testing Container Package v2

on:
  workflow_dispatch:
  push:
    paths:
    - '!.github/**'

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5

    env:
      base_tag:     ghcr.io/eth-cscs/slurm-container-${{ matrix.version }}:latest
      cache_tag:    ghcr.io/eth-cscs/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build tester image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ci/Dockerfile
        push: true
        tags: ${{ env.cache_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: 
          DOCKER_CONTAINER=${{ env.base_tag }}
                
  run-tests:
    needs: build-test-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5    
          
    container:
      image: ghcr.io/eth-cscs/cache_docker/slurm-uenv-mount-tester-${{ matrix.version }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        NODE_HW: CPUS=2
      options: --cpus 2 --privileged

    steps:
      - uses: actions/checkout@v3
      - run: make build install
      - run: make test
      - run: make rpm BUILD_DIR=/build
      
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: slurm-uenv-mount-${{ matrix.version }}
          assets: '*'
        continue-on-error: true
      
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: slurm-uenv-mount-${{ matrix.version }}
          tag_name: slurm-uenv-mount-${{ matrix.version }}
          files: |
            /usr/local/lib64/libslurm-uenv-mount.so
            /build/rpm/SRPMS/*
            /build/rpm/RPMS/**
